version: '3.8'

services:
    # 1. MQTT Broker (Sử dụng Mosquitto nội bộ)
  local-mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: local_mqtt_broker
    ports:
      - "1883:1883"
    networks:
      - iot_network

    # Cần tạo file cấu hình cho phép kết nối bên ngoài nếu muốn dùng iPhone
    # volumes:
    #   - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  
  node-red:
    image: nodered/node-red:latest
    container_name: iiot_nodered
    user: "root" 
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "1880:1880"
    networks:
      - iot_network
    volumes:
      - ./node_red_data:/data # Lưu flows và cấu hình vào thư mục hiện tại
    restart: always

    # 2. Backend (FastAPI)
  local-backend:
    build: ./backend
    container_name: local_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - BROKER=local-mqtt-broker
      # SQLite sử dụng đường dẫn file thay vì địa chỉ host/port
      - DATABASE_URL=sqlite:///./sql_app.db
    networks:
      - iot_network
    links:
      - local-mqtt-broker
    depends_on:
      - local-mqtt-broker
    # Đã xóa postgres_db khỏi depends_on vì không còn dùng container DB riêng
    command: uvicorn fast_api:app --host 0.0.0.0 --port 8000 --reload

networks:
  iot_network:
    driver: bridge
